// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: FVE_HMI-32

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void sw1Event(lv_event_t * e);
void sw2Event(lv_event_t * e);
void sw3Event(lv_event_t * e);
void sw4Event(lv_event_t * e);
void btn2hEvent(lv_event_t * e);
void btn2htxt(lv_event_t * e);
void poolTimeSet(lv_event_t * e);
void saveSettings(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
