// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: FVE_HMI-32

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Switch4 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_ntpTime = NULL;
lv_obj_t * ui_btn2h = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -329);
    lv_obj_set_y(ui_Label1, -33);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Čerpadlo");
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_White);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch1, 72);
    lv_obj_set_height(ui_Switch1, 35);
    lv_obj_set_x(ui_Switch1, -230);
    lv_obj_set_y(ui_Switch1, -33);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0xFF9600), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch2, 72);
    lv_obj_set_height(ui_Switch2, 35);
    lv_obj_set_x(ui_Switch2, -229);
    lv_obj_set_y(ui_Switch2, -117);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xFF8200), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -314);
    lv_obj_set_y(ui_Label2, -116);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Měnič");
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_White);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -309);
    lv_obj_set_y(ui_Label3, 56);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Dílna");
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_White);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch3, 72);
    lv_obj_set_height(ui_Switch3, 35);
    lv_obj_set_x(ui_Switch3, -228);
    lv_obj_set_y(ui_Switch3, 53);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0xFF8600), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 800);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xE8A228), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch4 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch4, 72);
    lv_obj_set_height(ui_Switch4, 35);
    lv_obj_set_x(ui_Switch4, -230);
    lv_obj_set_y(ui_Switch4, 135);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0xFF8600), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image2, &ui_img_home_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_Image2, 40);
    lv_obj_set_y(ui_Image2, 12);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image2, 420);

    ui_ntpTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ntpTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ntpTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ntpTime, 297);
    lv_obj_set_y(ui_ntpTime, -217);
    lv_obj_set_align(ui_ntpTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ntpTime, "00:00:00");
    ui_object_set_themeable_style_property(ui_ntpTime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_ntpTime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_White);
    lv_obj_set_style_text_font(ui_ntpTime, &ui_font_Sans30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn2h = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_btn2h, 182);
    lv_obj_set_height(ui_btn2h, 41);
    lv_obj_set_x(ui_btn2h, -13);
    lv_obj_set_y(ui_btn2h, -34);
    lv_obj_set_align(ui_btn2h, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn2h, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn2h, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btn2h, lv_color_hex(0xE8A228), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn2h, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -12);
    lv_obj_set_y(ui_Label4, -34);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Sepnout na 2h");
    ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_White);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Sans, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label1 = NULL;
    ui_Switch1 = NULL;
    ui_Switch2 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Switch3 = NULL;
    ui_Panel3 = NULL;
    ui_Switch4 = NULL;
    ui_Image2 = NULL;
    ui_ntpTime = NULL;
    ui_btn2h = NULL;
    ui_Label4 = NULL;

}
